---
# handlers file for clickhouse
- name: restart-ch
  service:
    name: "clickhouse-server"
    state: restarted
  become: true

- name: restart-ch-systemd
  systemd:
    name: clickhouse-server
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: reload systemd daemon
  systemd:
    daemon_reload: true